version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Upgrading pip, setuptools, wheel..."
      - python -m pip install --upgrade pip setuptools wheel
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Creating deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py
      - echo "Uploading unsigned package to S3..."
      - aws s3 cp deployment_package.zip s3://function-sample-signer-bucket/unsigned-code/deployment_package.zip

  post_build:
    commands:
      - echo "Starting Lambda signing job..."
      - SIGNING_JOB_ID=$(aws signer start-signing-job \
          --source s3={bucket=function-sample-signer-bucket,key=unsigned-code/deployment_package.zip} \
          --destination s3={bucket=function-sample-signer-bucket,key=signed-code/signed_deployment_package.zip} \
          --profile-name github-to-lambda-demo-signer \
          --query 'jobId' --output text)
      - echo "Signing Job ID: $SIGNING_JOB_ID"
      - echo "Waiting for signing job to complete..."
      - aws signer wait job-complete --job-id $SIGNING_JOB_ID
      - echo "Updating Lambda function..."
      - aws lambda update-function-code \
          --function-name github-to-lambda-demo \
          --s3-bucket function-sample-signer-bucket \
          --s3-key signed-code/signed_deployment_package.zip
      - echo "DONE!!"
