version: 0.2

phases:
  install:
    runtime-versions:
      python: 3.12
    commands:
      - echo "Upgrading pip..."
      - python -m pip install --upgrade pip
      - echo "Installing dependencies..."
      - pip install -r requirements.txt -t lib

  build:
    commands:
      - echo "Zipping deployment package..."
      - cd lib
      - zip -r9 ../deployment_package.zip .
      - cd ..
      - zip -g deployment_package.zip lambda_function.py

  post_build:
    commands:
      - echo "Uploading unsigned code to S3..."
      - aws s3 cp deployment_package.zip s3://function-sample-signer-bucket/unsigned-code/deployment_package.zip
      - echo "Signing Lambda package..."
      - aws signer start-signing-job \
          --source s3={"bucketName":"function-sample-signer-bucket","key":"unsigned-code/deployment_package.zip"} \
          --destination s3={"bucketName":"function-sample-signer-bucket","key":"signed-code/"} \
          --profile-name github_to_lambda_demo_signer \
          --client-request-token $(date +%s)

      - echo "DONE!!"
